FROM python:3.9-slim

WORKDIR /app

# Install required packages
RUN pip install mysql-connector-python mimesis

# Copy the generator script
COPY data_generator.py .

CMD ["python", "data_generator.py"]